arch:
- armv7
- amd64
- i386
description: Free & Open-Source HTML5 Network Performance Estimation Tool
image: irakhlin/openspeedtest
init: false
name: OpenSpeedTest
ingress: true
slug: openspeedtest
url: https://hub.docker.com/r/openspeedtest/latest
version: v2.0.6
webui: http://[HOST]:[PORT:3000]
