arch:
- armv7
- amd64
- i386
description: Free & Open-Source HTML5 Network Performance Estimation Tool
image: irakhlin/openspeedtest
init: false
name: OpenSpeedTest
ingress: true
ingress_port: 6000
slug: openspeedtest
version: "1.1.3"
